	platform :ios, '7.0'

	source 'gitmovalys@git.ptx.fr.sopra:podspecs.git'
	source 'https://github.com/CocoaPods/Specs.git'

	use_frameworks!
	inhibit_all_warnings!

	pod 'MFCore', '1.5.1'
	pod 'MFUI', '1.5.1'

	post_install do |installer_representation|
		installer_representation.project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
				config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
				if target.name == "Pods-MFUI"
					config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = '$(CONFIGURATION_BUILD_DIR)'			end
			end
		end
	end
